#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST
  defaults:
    template: 'admin\user\index.html.twig'

logout:
  path: /logout
  
admin.property.index:
  path: /admin
  controller: App\Controller\Admin\AdminPropertyController::index
  methods: GET|POST
  defaults:
    template: 'admin/property/index.html.twig'
    
admin.user.index:
    path: /admin/user/index
    controller: App\Controller\Admin\UserController::index
    methods: GET
    defaults:
      template: 'admin\user\index.html.twig'

admin.user.new:
    path: /admin/user/new
    controller: App\Controller\Admin\UserController::new
    methods: GET|POST
    defaults:
      template: 'admin\user\new.html.twig'

admin.user.show:
    path: /admin/user/{id}/show
    controller: App\Controller\Admin\UserController::show
    methods: GET
    defaults:
      template: 'admin\user\show.html.twig'

admin.user.edit:
    path: /admin/user/{id}/edit
    controller: App\Controller\Admin\UserController::edit
    methods: GET|POST
    defaults:
      template: 'admin\user\edit.html.twig'

admin.user.delete:
    path: /admin/user/{id}/delete
    controller: App\Controller\Admin\UserController::delete
    methods: DELETE
    defaults:
      template: 'admin\user\_delete.html.twig'

admin.property.new:
    path: /admin/new
    controller: App\Controller\Admin\AdminPropertyController::new
    methods: GET|POST
    defaults:
      template: 'admin\property\new.html.twig'

admin.property.edit:
    path: /admin/{id}/edit
    controller: App\Controller\Admin\AdminPropertyController::edit
    methods: GET|POST
    defaults:
      template: 'admin\property\edit.html.twig'

admin.property.delete:
    path: /admin/{id}/delete
    controller: App\Controller\Admin\AdminPropertyController::delete
    methods: DELETE

admin.option.new:
    path: /admin/option/new
    controller: App\Controller\Admin\OptionController::new
    methods: GET|POST
    defaults:
      template: 'admin\option\new.html.twig'

admin.option.index:
    path: /admin/option/index
    controller: App\Controller\Admin\OptionController::index
    methods: GET
    defaults:
      template: 'admin\option\index.html.twig'

admin.option.edit:
    path: /admin/option/{id}/edit
    controller: App\Controller\Admin\OptionController::edit
    methods: GET|POST
    defaults:
      template: 'admin\option\edit.html.twig'

admin.option.show:
    path: /admin/option/{id}/show
    controller: App\Controller\Admin\OptionController::show
    methods: GET
    defaults:
      template: 'admin\option\show.html.twig'

admin.option.delete:
    path: /admin/option/{id}/delete
    controller: App\Controller\Admin\OptionController::delete
    methods: DELETE
    defaults:
      template: 'admin\option\_delete.html.twig'

home:
  path: /
  controller: App\Controller\HomeController::index

property.index:
  path: /biens
  controller: App\Controller\PropertyController::index
  
property.show:
  path: /{slug}/{id}/show
  controller: App\Controller\PropertyController::show
  




    
